import type { ComponentType } from "react";
import {
  NavbarPage,
  NavbarWithDropdownPage,
  FooterPage,
  HeroPage,
  PageHeaderPage,
  CardPage,
  GridPage,
  FormGridPage,
  DividerPage,
} from "./Layout.js";
import {
  ButtonPage,
  InputPage,
  SelectPage,
  SearchBarPage,
  CheckboxPage,
  RadioPage,
  SwitchPage,
} from "./Inputs.js";
import {
  BadgePage,
  TagPage,
  AlertPage,
  ToastPage,
  SkeletonPage,
  SpinnerPage,
} from "./Feedback.js";
import {
  TabsPage,
  SegmentedTabsPage,
  BreadcrumbPage,
  PaginationPage,
  ViewTogglePage,
  AccordionPage,
} from "./Navigation.js";
import {
  TablePage,
  AvatarPage,
  ImageBadgePage,
  InfoBlockPage,
  ModalPage,
} from "./DataDisplay.js";
import {
  ReformCardPage,
  ReformSectionPage,
  FeaturedHeroPage,
  ContactSectionPage,
} from "./Composite.js";

export const pages: Record<string, ComponentType> = {
  Navbar: NavbarPage,
  NavbarWithDropdown: NavbarWithDropdownPage,
  Footer: FooterPage,
  Hero: HeroPage,
  PageHeader: PageHeaderPage,
  Card: CardPage,
  Grid: GridPage,
  FormGrid: FormGridPage,
  Divider: DividerPage,
  Button: ButtonPage,
  Input: InputPage,
  Select: SelectPage,
  SearchBar: SearchBarPage,
  Checkbox: CheckboxPage,
  Radio: RadioPage,
  Switch: SwitchPage,
  Badge: BadgePage,
  Tag: TagPage,
  Alert: AlertPage,
  Toast: ToastPage,
  Skeleton: SkeletonPage,
  Spinner: SpinnerPage,
  Tabs: TabsPage,
  SegmentedTabs: SegmentedTabsPage,
  Breadcrumb: BreadcrumbPage,
  Pagination: PaginationPage,
  ViewToggle: ViewTogglePage,
  Accordion: AccordionPage,
  Table: TablePage,
  Avatar: AvatarPage,
  ImageBadge: ImageBadgePage,
  InfoBlock: InfoBlockPage,
  Modal: ModalPage,
  ReformCard: ReformCardPage,
  ReformSection: ReformSectionPage,
  FeaturedHero: FeaturedHeroPage,
  ContactSection: ContactSectionPage,
};
